image: python: 3.9.6

clone:
 depth: full

pipelines:
 default:
  -step:
    caches:
     -pip
    script: # Modify the commands below to build your repository.
     — pip install -r requirements.txt
     — git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD